### PR TITLE
fix depwarns under 0.7 and bump REQUIRE and CI to 0.6

### PR DESCRIPTION
**Pull request by Sacha0**
Best! :) (Pinging @staticfloat as requested in the issue/pr template.)

### CODE REVIEW

**Comment by staticfloat** [comment]
@tkelman what's the accepted wisdom here; should I make a 0.5-compatible branch and keep `master` working nicely on 0.7+?

**Comment by tkelman** [comment]
If this is annoying enough people, sure. Or put the 0.7-only fixes in a non master branch for a while, either way.

One thing to note is if dropping two julia versions at the same time, it may make sense to leave versioning room and bump package minor by two at the next tag.

**Comment by staticfloat** [comment]
Thanks @Sacha0!  I'll get a new version tagged and submitted to METADATA right away.

**Comment by Sacha0** [comment]
Thanks Elliot! :)

**Pull request merged**
