### PR TITLE
Added IO, show and copy tests.

### PR DESCRIPTION
**Pull request by vinctux**
Summary:

- Added IOStream test.
- Added `copy` test.
- Added `show` test.

Updates the mess I created as an inexperienced git user in #17. I'm truly sorry for that.

### CODE REVIEW

**Comment by staticfloat** [comment]
Great, once the tests come back green, I'll merge this and push this out as a new `SHA` release.

**Comment by vinctux** [comment]
Great! :+1:

BTW, ever thought of including other hash algorithms (like BLAKE etc.) into the suite? Naturally, `SHA.jl` wouldn't suit then but there isn't any `Hash.jl` around yet, AFAIK.

**Comment by staticfloat** [comment]
My motivation for writing this package was mostly to provide an easy, cross-platform method of ensuring files downloaded for [BinDeps.jl](https://github.com/JuliaLang/BinDeps.jl) could be authenticated, so unfortunately I don't have time to go and write other algorithms in Julia.  :)

That being said, I'm happy to see more useful algorithms implemented in Julia, and I'm always available (sometimes with a day or two of lag, if I'm crunched for time) for questions if you're having a hard time getting something working.

**Comment by vinctux** [comment]
Maybe I'll add some native implementations, who knows ;) I was fascinated of Julia since the very begging, and now I finally got some spare time to make some things that aren't implemented yet. RSA is one of the things I had already implemented, and in this week I'll try to publish my `Krypto.jl` 'futuristic' lib, hopefully also containing RLWE and ECC.

**Comment by staticfloat** [comment]
Thanks @vinctux!

**Pull request merged**
