### PR TITLE
Increase coverage

### PR DESCRIPTION
**Pull request by staticfloat**

### CODE REVIEW

**Comment by staticfloat** [comment]
@IainNZ and @kshyatt you two should be proud.  100% coverage, except for that pesky `module` statement.  :P

**Comment by kshyatt** [comment]
:star:

**Comment by IainNZ** [comment]
@kshyatt I think there is something off with line numbers since that switch to Base.parse, some 0-/1- indexing type thing that they handle differently

**Comment by IainNZ** [comment]
https://github.com/IainNZ/Coverage.jl/issues/81

**Pull request merged**
