### PR TITLE
Fix depwarn on 0.5 for ByteString

### PR DESCRIPTION
**Pull request by yuyichao**
`convert(Vector{UInt8}, str)` seems to be a non-copying way to get the underlying array. I'm not sure what the long term plan for aliasing is but at least this shouldn't break when the internal representation of string changes again.

### CODE REVIEW

**Comment by yuyichao** [comment]
Also (re)enable precompilation. There are many packages that depend on this package with precompilation enabled. Not enabling it here will cause error in those packages.

**Comment by yuyichao** [comment]
@staticfloat

**Comment by staticfloat** [comment]
Good point about precompilation, thanks for catching that.  Could you change the comment next to the old `ByteString` so that it reads `AbstractString` as well?

**Comment by yuyichao** [comment]
Done.

**Comment by staticfloat** [comment]
👍

**Pull request merged**
