### PR TITLE
enable precompilation

### PR DESCRIPTION
**Pull request by tkelman**
let's see if this works

### CODE REVIEW

**Comment by tkelman** [comment]
Why is Travis saying "This is not an active repository" ?

**Comment by staticfloat** [comment]
Commenting here to remind myself to ensure this works.  Whatever problems you were having with Travis, I think they're fixed.  Also with that change to `REQUIRE`, we should probably release a new version, yes?

**Comment by tkelman** [comment]
Don't think it needs to be immediate. The code may actually work with 0.2, I'm just assuming that hasn't been tested.

**Comment by staticfloat** [comment]
Awesome.  Without precompilation:

```
$ time ./julia -e "using SHA"

real    0m1.020s
user    0m1.015s
sys     0m0.108s
```

With precompilation:
```
$ time ./julia -e "using SHA"

real    0m0.570s
user    0m0.581s
sys     0m0.099s
```

And my raw Julia startup time is:
```
 time ./julia -e ""

real    0m0.391s
user    0m0.408s
sys     0m0.093s
```

That's a hefty improvement!  Nice!

**Pull request merged**
