### PR TITLE
Fix 0.6 abstract type declaration depwarn

### PR DESCRIPTION
**Pull request by yuyichao**
~~**DO NOT MERGE NOW!!!!**~~

~~This requires https://github.com/JuliaLang/Compat.jl/pull/325 and a new tag. I'm using this (and other) PR's to check if the implementation is correct.~~

Ready now.

### CODE REVIEW

**Comment by yuyichao** [comment]
Compat tagged, CI reenabled.

**Comment by yuyichao** [comment]
@staticfloat

**Comment by staticfloat** [comment]
I'm amazed that Compat `0.17.0` still works on Julia `0.4.X`.

**Comment by yuyichao** [comment]
I don't think it'll be that hard to keep it working on 0.3 either (I still haven't delete my 0.3 tree yet....).

**Comment by tkelman** [comment]
Tim's about to delete a bunch of that code from Compat if nobody tells him not to.

**Pull request merged**
